discourse/discourse-post-voting

assets/javascripts/discourse/widgets/qa-comments.js.es6

This fixes an issue where posting an answer results in a JS error.

FIX: Do not error if there are no comments

---

app/controllers/question_answer/comments_controller.rb
app/models/question_answer_comment.rb
app/serializers/question_answer_comment_serializer.rb
assets/javascripts/discourse/widgets/qa-comments-menu.js
assets/javascripts/discourse/widgets/qa-comments.js
config/locales/server.en.yml
config/routes.rb
config/settings.yml
db/migrate/20211208073658_create_question_answer_comments.rb
extensions/post_extension.rb
extensions/post_serializer_extension.rb
extensions/topic_extension.rb
extensions/topic_view_extension.rb
extensions/user_extension.rb
plugin.rb
spec/fabricators/question_answer_comment_fabricator.rb
spec/lib/topic_view_spec.rb
spec/models/post_spec.rb
spec/models/question_answer_comment_spec.rb
spec/models/question_answer_vote_spec.rb
spec/models/topic_spec.rb
spec/requests/question_answer/comments_controller_spec.rb
spec/serializers/question_answer/comment_serializer_spec.rb
spec/serializers/question_answer/post_serializer_spec.rb
spec/serializers/question_answer/topic_view_serializer_spec.rb

This PR switches commenting in a Q&A topic to be backed by a custom class instead of using the `Post` model. This is done as we want to decouple ourselves from all the baggage that comes with the `Post` model. For example, creating a post bumps `Topic#highest_post_number` but the comments are not actually displayed as part of the post stream. This bump in the post number messes up unread making things hard to reason about.

FEATURE: Switch to a custom comments model.

---

assets/javascripts/discourse/initializers/qa-edits.js
extensions/topic_list_item_serializer_extension.rb
spec/requests/list_controller_spec.rb
test/javascripts/acceptance/question-answer-test.js

Per some internal discussions, this adds some logic for linking when there are unread posts in a Q&A topic. 
- when user has no unread posts, link to OP (unchanged, but logic moved to JS code)
- when user has one unread post, link to it
- when user has 2+ unread posts, link to first unread post and switch to sorting by activity
Sadly, I don't think we can easily add a useful test here. It would need to rely entirely on fixtures, which isn't ideal.

FEATURE: Add some logic for topic list linking

---

assets/stylesheets/mobile/question-answer.scss

Since https://github.com/discourse/discourse-question-answer/commit/e572ec7cab5293e56d8f7035041e52be63977d87, the `qa-is-answer` class is no longer used.

FIX: Mobile styling regression

---

app/controllers/question_answer/comments_controller.rb
assets/javascripts/discourse/widgets/qa-comment.js
assets/javascripts/discourse/widgets/question-answer-user-commented-notification-item.js
config/locales/client.en.yml
lib/question_answer/comment_creator.rb
plugin.rb
spec/requests/question_answer/comments_controller_spec.rb
test/javascripts/acceptance/notifications-test.js
test/javascripts/acceptance/question-answer-test.js

When a comment is created, we want to alert that creator of the post
where the comment is made. We may want to consider consolidatig
notifications in the future but this will do for the initial version of
the plugin.
To link to the comment, we rely on a hash fragment in the URL. Ideally,
we want to disable the post's highlight and highlight the comment
instead. However, this requires alot of hacking and our focus now is to
get an MVP out. If we really want to sugar coat this in the future, it
is still possible.

FEATURE: Create notification when a comment is created.

---

assets/javascripts/discourse/initializers/qa-edits.js
test/javascripts/acceptance/question-answer-test.js

There is some behaviour in core that tries to override the computed
properties in certain scenarios. Instead, I opted for the easier and
less risky way out here but relying on other post attributes to obtain
the same end result.

FIX: Avoid including computed property in widget/post attributes.

---

extensions/topic_view_extension.rb
plugin.rb
spec/lib/topic_view_spec.rb

Moneky patch core's method. In an ideal world, we wouldn't have to do this here but `TopicView` in core does not
yet properly support ordering posts in any other order except by `Post#sort_order` and several methods in
core's `TopicView` is strongly tied to the assumption that posts are always ordered by `Post#sort_order`. Fixing
core is hard and risky so we will just carry this monkey patch instead. There is also a small performance tradeoff
here in the following implementation. In PostgreSQL, we basically have to scan for every single posts in order
to figure out what the "row_number" for each post. From there, we can then properly fetch the window of posts
near a given post number.
Another alternative to this solution here is to rely on `Post#sort_order` and update the column of all …

FIX: Incorrect posts when loading posts near a given post number.

---

assets/javascripts/discourse/widgets/qa-comment-actions.js

No meaningful test I can add here unless we actually raise an error for a missing translation key used in the text environment.

FIX: Invalid translation key when deleting comment.

---

plugin.rb

Otherwise, the extensions are lost in development each time Rails
autoloader is activated.

DEV: Move extensions into reloadable patch.

---

assets/stylesheets/common/question-answer.scss

UX: add spacing between post controls and comments

---

assets/stylesheets/common/question-answer.scss
assets/stylesheets/mobile/question-answer.scss

UX: fix styling when Q&A topic is sorted by activity

---

assets/javascripts/discourse/widgets/qa-comment-editor.js
assets/javascripts/discourse/widgets/qa-comments-menu-composer.js
test/javascripts/acceptance/question-answer-test.js

This commit disables the comment submit button if the comment length is less than `min_post_length` or more than `qa_comment_max_raw_length`.
Before:
After:

FIX: disable submit comment button when required conditions are not met

---

assets/stylesheets/common/question-answer.scss

UX: wrap comments to prevent overflow

---

app/controllers/question_answer/votes_controller.rb
lib/question_answer/vote_manager.rb
spec/requests/question_answer/votes_controller_spec.rb

Currently the users could get around `qa_undo_vote_action_window` by
performing the inverse voting and thereby nullifying the vote. This
commit adds a verification to check if a user has already voted and
does not allow changing the vote after `qa_undo_vote_action_window`.

FIX: do not let users bypass qa_undo_vote_action_window

---

extensions/composer_messages_finder_extension.rb
plugin.rb
spec/components/composer_messages_finder_spec.rb

Suppresses the sequential replies education message for Q&A topics.

FIX: do not warn users for sequential replies on Q&A topic

---

spec/requests/topics_controller_spec.rb

Temporarily disable crawler view test while we work on perf issues.

Temporarily disable crawler view test

---

assets/javascripts/discourse/initializers/qa-edits.js

ref: https://github.com/discourse/discourse/commit/abe9b41ddf1a0481f1450d9a56e846aa3367f365
meta ref: https://meta.discourse.org/t/sort-by-activity-in-q-a-does-not-work/234591

FIX: fix typo per upstream changes

---

extensions/topic_extension.rb
spec/models/topic_spec.rb

Flakes were:
```
1) Topic should return correct last_commented_on
Failure/Error: expect(topic.last_commented_on).to eq_time(expected)
2022-08-17 11:02:51 UTC is not within 1 millisecond of 2022-08-17 11:02:51 UTC
2) Topic should return correct comments
Failure/Error: expect(comment_ids).to eq(topic_comment_ids)
expected: [110, 106, 107, 108, 109]
got: [106, 107, 108, 109, 110]
(compared using ==)
```

DEV: Fix flaky specs and make comment order consistent

---

test/javascripts/acceptance/composer-test.js

It was targetting a sk title instead of a dropdown. This was triggering warnings: "You expected select-kit to be expanded but it is collapsed."

DEV: Fix select-kit helper usage

---

assets/javascripts/discourse/connectors/category-custom-settings/question-answer-category-settings.hbs
assets/javascripts/discourse/initializers/extend-composer-actions.js
config/locales/client.en.yml
lib/question_answer/engine.rb
plugin.rb
spec/serializers/question_answer/basic_category_serializer_spec.rb
test/javascripts/acceptance/composer-test.js

@techAPJ This is a draft for "[Add setting QuestionAnswer at the category level](https://meta.discourse.org/t/add-setting-questionanswer-at-the-category-level/235040)". Just checking we're on the same page.

Add create as qa default category setting

---

.tx/config
README.md
assets/javascripts/discourse/initializers/extend-composer-actions.js
assets/javascripts/discourse/initializers/qa-edits.js
package.json
plugin.rb

A functional name change. The "Q&A" name carries a lot of meaning which this plugin is not intended for. Part 1 is just plugin name change, part 2 will include filenames and symbols.
t/52356/146
Screenshot to prove it's functional:

DEV: Rename plugin to discourse-upvotes part 1

---

spec/requests/posts_controller_spec.rb

See https://github.com/discourse/discourse/pull/18437, we are removing any references to enable_personal_messages in core and using only personal_message_enabled_groups, which requires auto groups to be assigned in certain specs for them to keep working.

DEV: Fix specs for personal_message_enabled_groups setting

---

db/migrate/20211020062413_create_question_answer_votes.rb

We’ll be dropping support to convert the old plugin's data to this plugin due to contamination in the `vote_history` column. eg. `  "\"[\\\"[{\\\\\\\"direction\\\\\\\":\\\\\\\"up\\\\\\\",\\\\\\\"action\\\\\\\":\\\\\\\"create\\\\\\\",\\\\\\\"user_id\\\\\\\":51,\\\\\\\"created_at\\\\\\\":\\\\\\\"2018-11-02T14:21:49.785+00:00\\\\\\\"}]\\\",{\\\"direction\\\":\\\"up\\\",\\\"action\\\":\\\"create\\\",\\\"user_id\\\":61,\\\"created_at\\\":\\\"2018-11-15T18:49:43.875+00:00\\\"}]\"",
`. See post by [Jay](https://meta.discourse.org/t/question-answer-plugin/56032/301?u=nat)
For folks who wish to have that compatibility, we will be happy to accept community help for a rake task which can migrate the data safely.
https://meta.discourse.org/t/plugin-causing-errors-during-rebuild/241110

DEV: Drop support for upgrade Pavilion's discourse-question-answer plugin

---

.prettierrc

Plugin skeleton indicates an empty prettier. https://github.com/discourse/discourse-plugin-skeleton/blob/main/.prettierrc

DEV: Empty prettier as per skeleton

---

assets/stylesheets/common/question-answer.scss

The commit contains a fix to the location of the answer header sorts buttons in RTL mode. In the image below you can see the change:
- On the top, you can see the current status - the location of the buttons is on the right (which is wrong).
- On the bottom, you can see the fix - the location of the buttons is on the left (which is correct).
Steps to reproduce the issue:
- Setup a new and clean Discourse instance.
- In settings, under "default locale" choose some RTL language (for example Hebrew).
- Create a new QA post with one answer and check the sorting buttons.

FIX: adjust QA answers header sorts in RTL mode

---

.tx/config
README.md
assets/javascripts/discourse/initializers/extend-composer-actions.js
assets/javascripts/discourse/initializers/qa-edits.js
package.json
plugin.rb

Slicing https://github.com/discourse/discourse-post-voting/pull/110 since it's too big for reviewing -- renaming just the plugin.

DEV: Rename plugin to discourse-post-voting

---

extensions/post_serializer_extension.rb
spec/requests/posts_controller_spec.rb

This was not always the case before because @topic_view was not set for
new posts. This had the unfortunate effect of not rendering the post as
a post-voting post, which meant there was no way to create a comment
without a page refresh after creating a post.

FIX: Returns all post-voting fields for new posts

---

extensions/post_extension.rb
plugin.rb
spec/lib/email/receiver_spec.rb

Previosuly, it was added as embedded replies (post comments) instead of answers.

FIX: treat reply to first posts via email as answers.

---

assets/javascripts/discourse/connectors/category-custom-settings/post-voting-category-settings.hbs
test/javascripts/acceptance/category-edit-test.js

The setting `create_as_post_voting_default` should change the topic type to "post voting" when the category is selected in the composer while creating a new topic.

FIX: category setting `create_as_post_voting_default` is not working as expected.

---

extensions/post_extension.rb
spec/lib/topic_view_spec.rb

We have replaced the `#pluck_first` freedom patch with the native `#pick` in core [here](https://github.com/discourse/discourse/pull/19893).
This change is updates this plugin in the same fashion.

DEV: Replace #pluck_first monkey patch with native #pick

---

app/serializers/question_answer_comment_serializer.rb
assets/javascripts/discourse/components/post-voting-comment.hbs
assets/stylesheets/common/post-voting.scss
config/locales/client.en.yml
lib/post_voting/vote_manager.rb
plugin.rb
spec/components/post_voting/vote_manager_spec.rb
spec/serializers/question_answer/comment_serializer_spec.rb
test/javascripts/acceptance/post-voting-test.js

Serializing topics with deleted comment users results in unhandled errors.
This change guards the user details access on `QuestionAnswerComment` records and also cleans up post voting related records when a user is destroyed via UserDestroyer.

FIX: Comment serialization for deleted users

---

assets/stylesheets/common/post-voting.scss
plugin.rb
spec/lib/topic_view_spec.rb

Related meta topic: https://meta.discourse.org/t/whispers-and-small-action-posts-disappear-in-post-voting-topic/267567
The bug now is that in both Sort by "Votes" and Sort by "Activity", we are not showing small action posts when a topic is closed, archived, or an assignment.
This commit removes the filter when sorting by activity, since it is chronological and makes sense for small action posts to be in between votes.
Related:
There is still an outstanding bug where due to Sort by "Activity" being a `?filter=activity`, when a topic is closed, the returning post stream is empty and doesn't update the topic. That will be fixed in a separate PR.

FIX: Show small action posts when sorted by activity

---

assets/stylesheets/common/post-voting.scss

`var(--topic-body-width) + var(--topic-body-width-padding) * 2` comes from `.topic-body`, and `45px` comes from `.topic-avatar`.
Before:
After:

UX: Align the sort by buttons to the right of the post

---

assets/stylesheets/common/post-voting.scss
assets/stylesheets/desktop/post-voting.scss
assets/stylesheets/mobile/post-voting.scss
plugin.rb

As part of https://github.com/discourse/discourse-post-voting/pull/164 this bug was introduced where the two buttons would be far on the right in mobile.
This introduces a specific desktop stylesheet so the width set in the earlier PR can be applied to it.

UX: Unset width for sorting methods on mobile

---

db/post_migrate/20230908045625_drop_question_answer_tables.rb

They've been migrated to `post_voting_x`. So we can now safely drop them.
https://github.com/discourse/discourse-post-voting/pull/163

DEV: Drop unused tables

---

plugin.rb
spec/lib/topic_view_spec.rb

Why this change?
A topic with post voting enabled will fail to render on the client side
when there is only the first post in the topic and the post is converted
to the `moderator_action` subtype.
This plugin adds a custom filter when fetching posts which is supposed to filter out
small actions and whispers. However, we were doing this in an incorrect
manner by filtering only for `regular` posts.
What does this change do?
This change updates our query filter to filter way whispers and small
actions instead of just filtering for regular topics.

FIX: Post voting topic broken when OP is moderator action

---

plugin.rb

This may be the cause of `/categories` returning a 500. (Hard to say for sure, I don't have a local repro.)

HOTFIX: Add category list preloading

---

spec/lib/email/receiver_spec.rb
spec/system/post_voting_spec.rb

In https://github.com/discourse/discourse/pull/24740, `min_trust_to_create_topic` site setting was replaced by `create_topic_allowed_groups`. This PR replaces the former, deprecated one, with the latter.

DEV: Replace deprecated min_trust_to_create_post

---

assets/javascripts/discourse/initializers/extend-composer-actions.js

**Context**
`discourse-customize-new-topic-button-text ` is a theme component that allows to customize the new topic button in different ways
**Problem**
For some reason, the post-voting plugin overrides the `discourse-customize-new-topic-button-text` behaviour and doesn't allow the user to customize the new topic button 
**Solution**
Add a hook so the initializer can be executed in an order where `discourse-customize-new-topic-button-text` theme component can customize the new topic button

FIX: Customize New Button Compatibility with Post Voting Plugin

---

assets/javascripts/discourse/components/post-voting-comment-actions.js
config/locales/server.en.yml
config/settings.yml
db/post_migrate/20240122015930_fill_flag_post_voting_comments_allowed_groups_based_on_deprecated_setting.rb
lib/post_voting/guardian_extension.rb
plugin.rb

New setting is flag_posts_voting_comments_allowed_groups
c.f. https://meta.discourse.org/t/changes-coming-to-settings-for-giving-access-to-features-from-trust-levels-to-groups/283408

DEV: Change min_trust_to_flag_posts_voting_comments to group setting

---

extensions/topic_view_extension.rb
spec/lib/topic_view_spec.rb

**Context**
Currently, we have a monkey patch for Post voting plugin posts that allows us to load posts based a on different order than what `Post#sort_order` does. 
**Problem**
This is causing issues with crawlers (JS disabled) since we are displaying a `next_page` button that should not be there. This happens because the `next_page` logic is based on the supposition that the Post order is what `Post#sort_order` outputs. 
**Solution**
Make a `next_page` method that overrides core's implementation for Post voting Posts and works correctly with the custom order used in the plugin

FIX: Next Page issues with crawlers

---

plugin.rb
spec/models/topic_embed_spec.rb

This commit registers a modifier to set the subtype of a topic to `Topic::POST_VOTING_SUBTYPE` during the embedding process when certain conditions are met:
- a new topic is being created;
- the topic will be saved to a valid category;
- the category has either `create_as_post_voting_default` or `only_post_voting_in_this_category` set to `true`
This PR requires https://github.com/discourse/discourse/pull/26527 to be merged in core. DO NOT MERGE before that.

FIX: Set topic subtype when embedding topics

---

config/locales/server.en.yml

I am trying to enable `i18n.raise_on_missing_translations` in core. It caught a missing translation in this plugin. The translation is used as a reason for auto-silencing a user, so it has gone unnoticed until now.
**Before:**
```
Randomized with seed 58289
......FF
Failures:
1) ReviewablePostVotingComment when the flagged comment author is silenced perform_disagree_and_restore unsilences the user
Failure/Error: raise I18n::MissingTranslationData.new(locale, key)
I18n::MissingTranslationData:
Translation missing: en.post_voting.comment.errors.auto_silence_from_flags
2) ReviewablePostVotingComment when the flagged comment author is silenced perform_disagree unsilences the user
Failure/Error: raise I18n::MissingTranslationData.new(locale, key)
I18n::MissingTranslationData:
Translation …
```

FIX: Add missing flag auto-silence reason translation

---

spec/plugin_helper.rb

The primary key is usually a bigint column, but the foreign key columns usually are of integer type. This can lead to issues when joining these columns due to mismatched types and different value ranges.
In a recent core change, all bigint sequences will start at a very high value in the test environment to surface this type of errors. The same change also added a temporary API that changes the column type to bigint in order to allow for the tests to run.
The plugin API is only temporary and it is important for these plugins to migrate their columns to bigint to avoid issues in the future.

DEV: Fix mismatched column types in tests

---

db/migrate/20241025132600_alter_post_voting_ids_to_bigint.rb
spec/plugin_helper.rb

The primary key is usually a bigint column, but the foreign key columns are usually of integer type. This can lead to issues when joining these columns due to mismatched types and different value ranges.
This was using a temporary plugin / test API to make tests pass, but it is safe to alter these tables because they usually have less than 1M rows and migration is going to be fast.

DEV: Fix mismatched column types

---

plugin.rb
spec/models/reviewable_post_voting_comment_spec.rb

Currently, when the user is deleted we remove comments and votes.
However, if there is a linked reviewable to comment, it should be deleted as well because it cannot be actioned.
In addition, reviewable should be registered so it is available in admin filter.

FIX: delete reviewable when the user is deleted

---

test/javascripts/acceptance/post-voting-test.js
test/javascripts/acceptance/post-voting-widget-post-menu-test.js

Matching on `#login-form` means these pass for modal or full page login screens. (See failures in https://github.com/discourse/discourse/pull/31771)

DEV: Update login screen checks in frontend tests
