discourse/discourse-post-voting

extensions/post_extension.rb, extensions/post_serializer_extension.rb, plugin.rb, spec/jobs/qa_update_topics_post_order_spec.rb, spec/serializers/question_answer/post_serializer_spec.rb, spec/serializers/question_answer/topic_view_serializer_spec.rb
The existing tests are failing so I had to fix them in the PR.
=> FIX: N+1 query when loading votes in `PostSerializer`.

app/serializers/question_answer/comment_serializer.rb, assets/javascripts/discourse/widgets/qa-comment.js.es6, assets/stylesheets/desktop/question-answer.scss, spec/requests/question_answer/comments_controller_spec.rb, spec/serializers/question_answer/comment_serializer_spec.rb
=> UX: Style comments in a more minimal way.

plugin.rb
Fetch comments with default id order scope.
=> DEV: Fix flaky specs due to ordering.

assets/javascripts/discourse/initializers/qa-edits.js, assets/stylesheets/common/question-answer.scss, assets/stylesheets/desktop/question-answer.scss, assets/stylesheets/mobile/question-answer.scss
=> UX: Mobile styling.

assets/javascripts/discourse/widgets/qa-comment.js, assets/stylesheets/common/question-answer.scss
=> UX: Change the display of comments to be more Discourse like.

app/models/question_answer_vote.rb, assets/javascripts/discourse/initializers/qa-edits.js, spec/models/question_answer_vote_spec.rb
Discussed this internally and we decided that the first post of a topic should be votable. This allows us to sort questions in the future by votes.
=> FEATURE: Allow voting on the first post of a topic.

assets/javascripts/discourse/widgets/qa-comment.js, assets/stylesheets/common/question-answer.scss
This reverts commit e0b123a838736e6056981d7c7f6bbcd1b64939d7.
Go with the more compact version for now.
=> UX: Change display of comment take 2.

app/controllers/question_answer/votes_controller.rb, app/models/question_answer_comment.rb, app/models/question_answer_vote.rb, app/serializers/question_answer_comment_serializer.rb, assets/javascripts/discourse/widgets/qa-comment.js, assets/stylesheets/common/question-answer.scss, assets/stylesheets/mobile/question-answer.scss, config/locales/server.en.yml, config/routes.rb, db/migrate/20220208071734_add_polymorphic_columns_to_question_answer_votes.rb, db/migrate/20220209070445_add_qa_vote_count_to_question_answer_comments.rb, extensions/post_extension.rb, extensions/post_serializer_extension.rb, extensions/topic_extension.rb, extensions/topic_view_extension.rb, lib/question_answer/vote_manager.rb, plugin.rb, spec/components/question_answer/vote_manager_spec.rb, spec/fabricators/question_answer_vote_fabricator.rb, spec/lib/topic_view_spec.rb, spec/models/question_answer_comment_spec.rb, spec/models/question_answer_vote_spec.rb, spec/models/topic_spec.rb, spec/requests/question_answer/votes_controller_spec.rb, spec/serializers/question_answer/comment_serializer_spec.rb, spec/serializers/question_answer/topic_view_serializer_spec.rb, test/javascripts/acceptance/question-answer-test.js
=> FEATURE: Allow comments to be voted on.

app/controllers/question_answer/votes_controller.rb, assets/javascripts/discourse/lib/qa-utilities.js, config/locales/client.en.yml, config/routes.rb, spec/requests/question_answer/votes_controller_spec.rb
This feature is not relevant in our new design.
=> DEV: Remove more stale code.

assets/javascripts/discourse/components/qa-topic-page-class.js, assets/javascripts/discourse/connectors/topic-title/add-qa-topic-page-class.hbs, test/javascripts/acceptance/question-answer-test.js
Follow-up to 5ec5c568406287187c05f7571ea425e9eb6a0049
=> FIX: Do not append Q&A specific class to body tag.

plugin.rb
The plugin no longers rely on the filtered post reply view.
=> DEV: Remove unnecessary code.

app/controllers/question_answer/comments_controller.rb, assets/javascripts/discourse/initializers/qa-edits.js, assets/javascripts/discourse/widgets/qa-comment.js, assets/javascripts/discourse/widgets/qa-comments.js, assets/stylesheets/common/question-answer.scss, spec/requests/question_answer/comments_controller_spec.rb, test/javascripts/acceptance/question-answer-test.js
=> FEATURE: Live updates when a comment is deleted.

app/controllers/question_answer/votes_controller.rb, app/models/question_answer_vote.rb, assets/javascripts/discourse/widgets/qa-button.js, config/locales/server.en.yml, spec/lib/topic_view_spec.rb, spec/models/question_answer_vote_spec.rb, spec/requests/question_answer/votes_controller_spec.rb, test/javascripts/acceptance/question-answer-test.js
This commit disables the voting option on self authored answers and comments.
=> FIX: do not allow voting on self answer or comment

assets/javascripts/discourse/initializers/extend-composer-actions.js, assets/javascripts/discourse/initializers/qa-edits.js, config/locales/client.en.yml, test/javascripts/acceptance/question-answer-test.js
=> UX: update label from reply to answer on Q&A topics

config/locales/client.en.yml
=> UX: update submit comment button label

Gemfile.lock, spec/components/composer_messages_finder_spec.rb, spec/models/post_spec.rb, spec/models/question_answer_comment_spec.rb, spec/models/question_answer_vote_spec.rb, spec/models/topic_spec.rb, spec/serializers/question_answer/basic_category_serializer_spec.rb, spec/serializers/question_answer/post_serializer_spec.rb
Updates rubocop-discourse version
=> DEV: Bump rubocop-discourse

assets/stylesheets/common/post-voting.scss
These are now CSS custom properties in core.
=> DEV: update box shadow

spec/requests/posts_controller_spec.rb
Needed for: https://github.com/discourse/discourse/pull/24578
=> DEV: Use auto refresh groups

app/models/post_voting_comment.rb, app/models/post_voting_comment_custom_field.rb, db/migrate/20231218171020_add_post_voting_comment_custom_fields.rb, db/migrate/20231220042344_add_last_editor_to_post_voting_messages.rb, db/migrate/20231220043117_make_post_voting_comment_last_editor_ids_not_null.rb, plugin.rb
**Context**
As part of implementing reviewables for post-voting comments in the Akismet plugins there are some changes required in the post-voting plugin such as custom fields and the last editor for post-voting comments
=> FEATURE: Implemented Custom Fields and last editor for Post Voting Comments

test/javascripts/acceptance/post-voting-test.js
This should unblock https://github.com/discourse/discourse/pull/25340
=> DEV: Add missing passkey challenge pretender

spec/models/post_voting_comment_spec.rb
Adjust spec to make it work after https://github.com/discourse/discourse/pull/26469 is merged.
=> DEV: Fix spec because of translation change in core

test/javascripts/acceptance/composer-test.js
> You expected select-kit to be expanded but it is collapsed.
=> DEV: Remove a test warning

assets/javascripts/discourse/components/post-voting-answer-button.gjs, assets/javascripts/discourse/initializers/post-voting-edits.gjs, test/javascripts/acceptance/post-voting-test.js, test/javascripts/acceptance/post-voting-widget-post-menu-test.js
Requires https://github.com/discourse/discourse/pull/28670
=> DEV: Added compatibility with the Glimmer Post Menu
